static const char *g_shader_src =
"#include <metal_stdlib>\n"
"using namespace metal;\n"
"#ifdef HW_RT\n"
"# include <metal_raytracing>\n"
"using namespace raytracing;\n"
"/*\n"
"** Con una sola copia del modelo (MESH_INST sin definir) la malla va en una\n"
"** estructura primitiva directa: sin el nivel de instancias, que cuesta ~30%.\n"
"*/\n"
"# ifdef MESH_INST\n"
"#  define MESH_ACCEL instance_acceleration_structure\n"
"#  define MESH_TAGS triangle_data, instancing\n"
"# else\n"
"#  define MESH_ACCEL primitive_acceleration_structure\n"
"#  define MESH_TAGS triangle_data\n"
"# endif\n"
"# define ACCEL_DECL primitive_acceleration_structure accel, \\\n"
"	intersection_function_table<> table, \\\n"
"	MESH_ACCEL mesh_accel, \\\n"
"	intersection_function_table<MESH_TAGS> mesh_table, \\\n"
"	device const t_gpu_tri *tris, device const GpuMaterial *mats, \\\n"
"	device const packed_float3 *mesh_pos, device const float4 *insts, \\\n"
"	texture2d<float> env_map\n"
"# define ACCEL_ARGS accel, table, mesh_accel, mesh_table, tris, mats, \\\n"
"	mesh_pos, insts, env_map\n"
"#else\n"
"# define ACCEL_DECL device const t_gpu_node *nodes, texture2d<float> env_map\n"
"# define ACCEL_ARGS nodes, env_map\n"
"#endif\n"
"\n"
"/*\n"
"** Tipos compartidos entre la CPU (C / Objective-C) y la GPU (Metal).\n"
"** Solo se usan vec4 y escalares de 4 bytes para que el layout de memoria\n"
"** sea identico en los dos lados.\n"
"*/\n"
"\n"
"#ifndef SHARED_H\n"
"# define SHARED_H\n"
"\n"
"# ifdef __METAL_VERSION__\n"
"\n"
"typedef float4	t_vec4;\n"
"\n"
"# else\n"
"#  include <simd/simd.h>\n"
"\n"
"typedef simd_float4	t_vec4;\n"
"\n"
"# endif\n"
"\n"
"# define GPU_SPHERE 0\n"
"# define GPU_PLANE 1\n"
"# define GPU_SQUARE 2\n"
"# define GPU_CYLINDER 3\n"
"# define GPU_TRIANGLE 4\n"
"\n"
"/*\n"
"** a: centro (esfera, cuadrado, cilindro), punto (plano) o vertice 1\n"
"** b: normal (plano, cuadrado), eje (cilindro) o vertice 2\n"
"** c: eje u del cuadrado o vertice 3\n"
"** color: rgb lineal (ya corregido de gamma)\n"
"*/\n"
"\n"
"typedef struct	s_gpu_object\n"
"{\n"
"	t_vec4		a;\n"
"	t_vec4		b;\n"
"	t_vec4		c;\n"
"	t_vec4		color;\n"
"	float		radius;\n"
"	float		height;\n"
"	float		reflect;\n"
"	int			type;\n"
"}				t_gpu_object;\n"
"\n"
"/*\n"
"** Nodo del BVH (32 bytes). Si count > 0 es una hoja con los objetos\n"
"** [first, first + count); si no, sus hijos son first y first + 1.\n"
"*/\n"
"\n"
"typedef struct	s_gpu_node\n"
"{\n"
"	float		minx;\n"
"	float		miny;\n"
"	float		minz;\n"
"	int			first;\n"
"	float		maxx;\n"
"	float		maxy;\n"
"	float		maxz;\n"
"	int			count;\n"
"}				t_gpu_node;\n"
"\n"
"/*\n"
"** Atributos de un triangulo de malla (.obj), 40 bytes: coordenadas de\n"
"** textura de sus 3 vertices, normales de vertice comprimidas (octaedro,\n"
"** 2 x 16 bits) e indice de material.\n"
"*/\n"
"\n"
"typedef struct	s_gpu_tri\n"
"{\n"
"	float		uv[6];\n"
"	unsigned int	n[3];\n"
"	unsigned int	material;\n"
"}				t_gpu_tri;\n"
"\n"
"# define MAT_TEXTURE 1\n"
"# define MAT_ALPHA 2\n"
"# define MAT_NORMAL 4\n"
"# define MAT_ROUGH 8\n"
"# define MAT_METAL 16\n"
"\n"
"typedef struct	s_gpu_light\n"
"{\n"
"	t_vec4		position;\n"
"	t_vec4		color;\n"
"}				t_gpu_light;\n"
"\n"
"typedef struct	s_gpu_frame\n"
"{\n"
"	t_vec4		origin;\n"
"	t_vec4		forward;\n"
"	t_vec4		right;\n"
"	t_vec4		up;\n"
"	t_vec4		ambient;\n"
"	float		fov;\n"
"	int			nobjects;\n"
"	int			nlights;\n"
"	int			samples;\n"
"	int			nplanes;\n"
"	int			pass;\n"
"	int			ntris;\n"
"	int			nopaque;\n"
"	float		spread;\n"
"	int			ao_rays;\n"
"	unsigned int	frame;\n"
"	int			pad;\n"
"	t_vec4		scene_min;\n"
"	t_vec4		scene_max;\n"
"	t_vec4		prev_origin;\n"
"	t_vec4		prev_forward;\n"
"	t_vec4		prev_right;\n"
"	t_vec4		prev_up;\n"
"	t_vec4		jitter;\n"
"	t_vec4		sun_dir;\n"
"	t_vec4		sun_color;\n"
"	t_vec4		env;\n"
"}				t_gpu_frame;\n"
"\n"
"#endif\n"
"\n"
"#ifdef HW_RT\n"
"\n"
"/*\n"
"** Material de malla. La textura es una referencia sin enlazar (Metal 3):\n"
"** el host escribe su gpuResourceID en el mismo sitio (32 bytes en total).\n"
"*/\n"
"\n"
"struct			GpuMaterial\n"
"{\n"
"	float4				kd;\n"
"	texture2d<float>	diffuse;\n"
"	texture2d<float>	normal;\n"
"	texture2d<float>	rough;\n"
"	texture2d<float>	metal;\n"
"	float				roughness;\n"
"	float				metallic;\n"
"	uint				flags;\n"
"	uint				pad;\n"
"};\n"
"\n"
"constexpr sampler	tex_sampler(address::repeat, filter::linear,\n"
"						mip_filter::linear);\n"
"#endif\n"
"\n"
"/*\n"
"** Port a Metal de generateImage/shading.c: mismas intersecciones y mismo\n"
"** sombreado (Blinn-Phong + sombras + reflejos + supersampling + gamma).\n"
"** Cada hilo de la GPU calcula un pixel.\n"
"*/\n"
"\n"
"constant int	MAX_DEPTH = 5;\n"
"constant float	SPECULAR = 0.4;\n"
"constant float	MESH_SPECULAR = 0.05;\n"
"constant float	SHININESS = 60;\n"
"constant float	GAMMA = 2.2;\n"
"constant float	EPSILON = 1e-3;\n"
"constant float	EXPOSURE = 1.0;\n"
"constant int	GI_BOUNCES = 2;\n"
"constant int	GI_SHADOW_BOUNCES = 3;\n"
"constant float	BOUNCE_LOD_BIAS = 3.0f;\n"
"constant float	CLIP_NEAR = 0.05f;\n"
"constant float	CLIP_FAR = 1000.0f;\n"
"constant float	SKY_LIGHT = 2.0;\n"
"constant float	GI_EXPOSURE = 2.2;\n"
"constant float	AO_RADIUS = 1.5;\n"
"constant float	EDGE = 0.1;\n"
"constant float	SHADOW_MIN_WEIGHT = 0.25;\n"
"constant float	TMIN = 1e-3;\n"
"constant float	NOHIT = 1e30f;\n"
"\n"
"struct			Hit\n"
"{\n"
"	float		t;\n"
"	float3		normal;\n"
"	int			id;\n"
"	float2		bary;\n"
"	bool		mesh;\n"
"	int			inst;\n"
"};\n"
"\n"
"static float	hit_plane(float3 o, float3 d, float3 p, float3 n)\n"
"{\n"
"	float den = dot(d, n);\n"
"\n"
"	if (fabs(den) < 1e-8)\n"
"		return (NOHIT);\n"
"	float t = dot(p - o, n) / den;\n"
"	return (t > TMIN ? t : NOHIT);\n"
"}\n"
"\n"
"static float	hit_sphere(float3 o, float3 d, float3 c, float r)\n"
"{\n"
"	float3 oc = o - c;\n"
"	float b = dot(oc, d);\n"
"	/*\n"
"	** Forma estable (Ray Tracing Gems, cap. 7): en vez de b^2 - |oc|^2,\n"
"	** que resta dos numeros enormes lejos del origen, se usa la distancia\n"
"	** del centro al rayo.\n"
"	*/\n"
"	float3 qc = oc - b * d;\n"
"	float h = r * r - dot(qc, qc);\n"
"\n"
"	if (h < 0)\n"
"		return (NOHIT);\n"
"	h = sqrt(h);\n"
"	if (-b - h > TMIN)\n"
"		return (-b - h);\n"
"	if (-b + h > TMIN)\n"
"		return (-b + h);\n"
"	return (NOHIT);\n"
"}\n"
"\n"
"static float	hit_square(float3 o, float3 d, device const t_gpu_object &obj)\n"
"{\n"
"	float3 n = obj.b.xyz;\n"
"	float t = hit_plane(o, d, obj.a.xyz, n);\n"
"\n"
"	if (t == NOHIT)\n"
"		return (NOHIT);\n"
"	float3 p = o + t * d - obj.a.xyz;\n"
"	float3 u = obj.c.xyz;\n"
"	float3 v = cross(n, u);\n"
"	float half_side = obj.height / 2;\n"
"	if (fabs(dot(p, u)) > half_side || fabs(dot(p, v)) > half_side)\n"
"		return (NOHIT);\n"
"	return (t);\n"
"}\n"
"\n"
"static float	hit_triangle(float3 o, float3 d, device const t_gpu_object &obj)\n"
"{\n"
"	float3 e1 = obj.b.xyz - obj.a.xyz;\n"
"	float3 e2 = obj.c.xyz - obj.a.xyz;\n"
"	float3 pv = cross(d, e2);\n"
"	float det = dot(e1, pv);\n"
"\n"
"	if (fabs(det) < 1e-8)\n"
"		return (NOHIT);\n"
"	float3 tv = o - obj.a.xyz;\n"
"	float u = dot(tv, pv) / det;\n"
"	if (u < 0 || u > 1)\n"
"		return (NOHIT);\n"
"	float3 qv = cross(tv, e1);\n"
"	float v = dot(d, qv) / det;\n"
"	if (v < 0 || u + v > 1)\n"
"		return (NOHIT);\n"
"	float t = dot(e2, qv) / det;\n"
"	return (t > TMIN ? t : NOHIT);\n"
"}\n"
"\n"
"/*\n"
"** Cilindro finito con tapas: lateral (raices de la cuadratica dentro de la\n"
"** altura) y dos discos en +-altura/2.\n"
"*/\n"
"\n"
"static float	hit_cylinder(float3 o, float3 d,\n"
"					device const t_gpu_object &obj, thread float3 &normal)\n"
"{\n"
"	float3 c = obj.a.xyz;\n"
"	float3 axis = obj.b.xyz;\n"
"	float r = obj.radius;\n"
"	float hh = obj.height / 2;\n"
"	float best = NOHIT;\n"
"	float3 oc = o - c;\n"
"	float da = dot(d, axis);\n"
"	float oa = dot(oc, axis);\n"
"	float3 dp = d - da * axis;\n"
"	float3 op = oc - oa * axis;\n"
"	float qa = dot(dp, dp);\n"
"	float qb = 2 * dot(dp, op);\n"
"	float disc = qb * qb - 4 * qa * (dot(op, op) - r * r);\n"
"\n"
"	if (qa > 1e-8 && disc >= 0)\n"
"	{\n"
"		float sq = sqrt(disc);\n"
"		float roots[2] = {(-qb - sq) / (2 * qa), (-qb + sq) / (2 * qa)};\n"
"		for (int i = 0; i < 2; i++)\n"
"		{\n"
"			float t = roots[i];\n"
"			if (t > TMIN && fabs(oa + t * da) <= hh)\n"
"			{\n"
"				best = t;\n"
"				normal = (op + t * dp) / r;\n"
"				break ;\n"
"			}\n"
"		}\n"
"	}\n"
"	for (int s = -1; s <= 1; s += 2)\n"
"	{\n"
"		float3 cap = c + s * hh * axis;\n"
"		float t = hit_plane(o, d, cap, axis);\n"
"		if (t < best && length(o + t * d - cap) <= r)\n"
"		{\n"
"			best = t;\n"
"			normal = s * axis;\n"
"		}\n"
"	}\n"
"	return (best);\n"
"}\n"
"\n"
"static float		hit_object(float3 o, float3 d, device const t_gpu_object &obj,\n"
"					thread float3 &normal)\n"
"{\n"
"	float t;\n"
"\n"
"	switch (obj.type)\n"
"	{\n"
"		case GPU_SPHERE:\n"
"			t = hit_sphere(o, d, obj.a.xyz, obj.radius);\n"
"			normal = o + t * d - obj.a.xyz;\n"
"			return (t);\n"
"		case GPU_PLANE:\n"
"			normal = obj.b.xyz;\n"
"			return (hit_plane(o, d, obj.a.xyz, obj.b.xyz));\n"
"		case GPU_SQUARE:\n"
"			normal = obj.b.xyz;\n"
"			return (hit_square(o, d, obj));\n"
"		case GPU_TRIANGLE:\n"
"			normal = cross(obj.b.xyz - obj.a.xyz, obj.c.xyz - obj.a.xyz);\n"
"			return (hit_triangle(o, d, obj));\n"
"		default:\n"
"			return (hit_cylinder(o, d, obj, normal));\n"
"	}\n"
"}\n"
"\n"
"#ifdef HW_RT\n"
"\n"
"/*\n"
"** Version con las unidades de ray tracing de la GPU: el hardware recorre\n"
"** el arbol de cajas y llama a shape_hit para la interseccion exacta.\n"
"** Los objetos del arbol empiezan despues de los planos (de ahi el offset\n"
"** del buffer en la tabla de funciones).\n"
"*/\n"
"\n"
"static float3	unpack_normal(uint v)\n"
"{\n"
"	if (v == 0)\n"
"		return (float3(0));\n"
"	float2 e = unpack_snorm2x16_to_float(v);\n"
"	float3 n = float3(e.x, e.y, 1 - fabs(e.x) - fabs(e.y));\n"
"	if (n.z < 0)\n"
"		n.xy = (1 - fabs(n.yx)) * select(float2(-1), float2(1), n.xy >= 0);\n"
"	return (normalize(n));\n"
"}\n"
"\n"
"static float3	inst_rotate(float3 v, float4 it)\n"
"{\n"
"	return (float3(it.x * v.x + it.y * v.z, v.y, -it.y * v.x + it.x * v.z));\n"
"}\n"
"\n"
"static float3	inst_point(float3 p, float4 it)\n"
"{\n"
"	return (inst_rotate(p, it) + float3(it.z, 0, it.w));\n"
"}\n"
"\n"
"static float2	tri_uv(device const t_gpu_tri &t, float2 b)\n"
"{\n"
"	return (float2(t.uv[0], t.uv[1]) * (1 - b.x - b.y)\n"
"		+ float2(t.uv[2], t.uv[3]) * b.x + float2(t.uv[4], t.uv[5]) * b.y);\n"
"}\n"
"\n"
"/*\n"
"** Hojas y demas materiales con transparencia: el hardware pregunta si el\n"
"** punto tocado del triangulo es opaco segun el canal alfa de la textura.\n"
"*/\n"
"\n"
"#ifdef MESH_INST\n"
"[[intersection(triangle, triangle_data, instancing)]]\n"
"#else\n"
"[[intersection(triangle, triangle_data)]]\n"
"#endif\n"
"bool			alpha_test(uint pid [[primitive_id]],\n"
"					float2 bary [[barycentric_coord]],\n"
"					device const t_gpu_tri *tris [[buffer(0)]],\n"
"					device const GpuMaterial *mats [[buffer(1)]],\n"
"					constant uint &base [[buffer(2)]])\n"
"{\n"
"	device const t_gpu_tri &t = tris[base + pid];\n"
"\n"
"	return (mats[t.material].diffuse.sample(tex_sampler, tri_uv(t, bary),\n"
"		level(0)).a >= 0.5f);\n"
"}\n"
"\n"
"struct			BoxResult\n"
"{\n"
"	bool		accept [[accept_intersection]];\n"
"	float		distance [[distance]];\n"
"};\n"
"\n"
"[[intersection(bounding_box)]]\n"
"BoxResult		shape_hit(float3 origin [[origin]],\n"
"					float3 direction [[direction]],\n"
"					float min_distance [[min_distance]],\n"
"					float max_distance [[max_distance]],\n"
"					uint id [[primitive_id]],\n"
"					device const t_gpu_object *objs [[buffer(0)]])\n"
"{\n"
"	float3	normal;\n"
"	float	t = hit_object(origin, direction, objs[id], normal);\n"
"\n"
"	BoxResult result = {t < NOHIT && t >= min_distance && t <= max_distance, t};\n"
"\n"
"	return (result);\n"
"}\n"
"\n"
"static Hit		intersect(float3 o, float3 d, constant t_gpu_frame &f,\n"
"					device const t_gpu_object *objs,\n"
"					ACCEL_DECL, float tmax, bool any)\n"
"{\n"
"	Hit		hit = {tmax, float3(0), -1};\n"
"	float3	normal;\n"
"	float	t;\n"
"\n"
"	for (int i = 0; i < f.nplanes; i++)\n"
"	{\n"
"		/*\n"
"		** Rayo de sombra que no cruza el plano: el plano no puede taparlo.\n"
"		*/\n"
"		if (any && dot(objs[i].b.xyz, o - objs[i].a.xyz)\n"
"			* dot(objs[i].b.xyz, o + d * tmax - objs[i].a.xyz) > 0)\n"
"			continue ;\n"
"		t = hit_object(o, d, objs[i], normal);\n"
"		if (t < hit.t)\n"
"		{\n"
"			hit = {t, normal, i};\n"
"			if (any)\n"
"				return (hit);\n"
"		}\n"
"	}\n"
"	if (f.ntris > 0)\n"
"	{\n"
"		intersector<MESH_TAGS> mi;\n"
"		mi.assume_geometry_type(geometry_type::triangle);\n"
"		mi.accept_any_intersection(any);\n"
"		ray mr(o, d, 0.0f, hit.t);\n"
"		intersection_result<MESH_TAGS> mres = mi.intersect(mr, mesh_accel,\n"
"			mesh_table);\n"
"		if (mres.type == intersection_type::triangle)\n"
"		{\n"
"			uint tri = (mres.geometry_id == 0 && f.nopaque > 0)\n"
"				? mres.primitive_id : f.nopaque + mres.primitive_id;\n"
"#ifdef MESH_INST\n"
"			int inst = (int)mres.instance_id;\n"
"#else\n"
"			int inst = 0;\n"
"#endif\n"
"			hit = {mres.distance, float3(0), (int)tri,\n"
"				mres.triangle_barycentric_coord, true, inst};\n"
"			if (any)\n"
"				return (hit);\n"
"		}\n"
"	}\n"
"	if (f.nobjects == f.nplanes)\n"
"		return (hit);\n"
"	/*\n"
"	** Si el rayo no toca la caja que envuelve todos los objetos, ni se\n"
"	** llama al hardware (p. ej. reflejos del suelo que suben al cielo).\n"
"	*/\n"
"	float3 inv = 1.0f / d;\n"
"	float3 t0 = (f.scene_min.xyz - o) * inv;\n"
"	float3 t1 = (f.scene_max.xyz - o) * inv;\n"
"	float3 lo = min(t0, t1);\n"
"	float3 hi = max(t0, t1);\n"
"	if (max(max(lo.x, lo.y), max(lo.z, 0.0f)) > min(min(hi.x, hi.y), min(hi.z, hit.t)))\n"
"		return (hit);\n"
"	intersector<> isect;\n"
"	isect.assume_geometry_type(geometry_type::bounding_box);\n"
"	isect.accept_any_intersection(any);\n"
"	ray r(o, d, 0.0f, hit.t);\n"
"	intersection_result<> res = isect.intersect(r, accel, table);\n"
"	if (res.type == intersection_type::bounding_box)\n"
"	{\n"
"		int i = res.primitive_id + f.nplanes;\n"
"		hit_object(o, d, objs[i], normal);\n"
"		hit = {res.distance, normal, i};\n"
"	}\n"
"	return (hit);\n"
"}\n"
"\n"
"#else\n"
"\n"
"/*\n"
"** Slab test: distancia de entrada a la caja, o NOHIT si no la toca antes\n"
"** de tmax.\n"
"*/\n"
"\n"
"static float	hit_box(float3 o, float3 inv, device const t_gpu_node &n,\n"
"					float tmax)\n"
"{\n"
"	float3 t0 = (float3(n.minx, n.miny, n.minz) - o) * inv;\n"
"	float3 t1 = (float3(n.maxx, n.maxy, n.maxz) - o) * inv;\n"
"	float3 lo = min(t0, t1);\n"
"	float3 hi = max(t0, t1);\n"
"	float tin = max(max(lo.x, lo.y), max(lo.z, 0.0f));\n"
"	float tout = min(min(hi.x, hi.y), min(hi.z, tmax));\n"
"	return (tin <= tout ? tin : NOHIT);\n"
"}\n"
"\n"
"#define STACK_SIZE 48\n"
"\n"
"/*\n"
"** any = true: rayo de sombra, vale con encontrar cualquier objeto antes\n"
"** de tmax (no hace falta el mas cercano).\n"
"*/\n"
"\n"
"static Hit		intersect(float3 o, float3 d, constant t_gpu_frame &f,\n"
"					device const t_gpu_object *objs,\n"
"					ACCEL_DECL, float tmax, bool any)\n"
"{\n"
"	Hit		hit = {tmax, float3(0), -1};\n"
"	float3	normal;\n"
"	float3	inv = 1.0f / d;\n"
"	int		stack[STACK_SIZE];\n"
"	int		sp = 0;\n"
"	float	t;\n"
"\n"
"	for (int i = 0; i < f.nplanes; i++)\n"
"	{\n"
"		t = hit_object(o, d, objs[i], normal);\n"
"		if (t < hit.t)\n"
"		{\n"
"			hit = {t, normal, i};\n"
"			if (any)\n"
"				return (hit);\n"
"		}\n"
"	}\n"
"	if (f.nobjects == f.nplanes || hit_box(o, inv, nodes[0], hit.t) == NOHIT)\n"
"		return (hit);\n"
"	stack[sp++] = 0;\n"
"	while (sp > 0)\n"
"	{\n"
"		device const t_gpu_node &node = nodes[stack[--sp]];\n"
"		if (node.count > 0)\n"
"		{\n"
"			for (int i = node.first; i < node.first + node.count; i++)\n"
"			{\n"
"				t = hit_object(o, d, objs[i], normal);\n"
"				if (t < hit.t)\n"
"				{\n"
"					hit = {t, normal, i};\n"
"					if (any)\n"
"						return (hit);\n"
"				}\n"
"			}\n"
"			continue ;\n"
"		}\n"
"		float tl = hit_box(o, inv, nodes[node.first], hit.t);\n"
"		float tr = hit_box(o, inv, nodes[node.first + 1], hit.t);\n"
"		int near = node.first;\n"
"		int far = node.first + 1;\n"
"		if (tr < tl)\n"
"		{\n"
"			float tmp = tl;\n"
"			tl = tr;\n"
"			tr = tmp;\n"
"			near = far;\n"
"			far = node.first;\n"
"		}\n"
"		if (tr != NOHIT && sp < STACK_SIZE)\n"
"			stack[sp++] = far;\n"
"		if (tl != NOHIT && sp < STACK_SIZE)\n"
"			stack[sp++] = near;\n"
"	}\n"
"	return (hit);\n"
"}\n"
"\n"
"#endif\n"
"\n"
"/*\n"
"** Cielo de las escenas con modelo: degradado de horizonte a cenit. En las\n"
"** escenas .rt clasicas el fondo sigue siendo negro.\n"
"*/\n"
"\n"
"constexpr sampler	env_sampler(address::repeat, filter::linear);\n"
"\n"
"/*\n"
"** Cielo: con HDRI (f.env.y > 0) se lee la foto de 360 grados en proyeccion\n"
"** equirectangular, girada f.env.z radianes; sin HDRI, un degradado.\n"
"*/\n"
"\n"
"static float3	sky(float3 d, constant t_gpu_frame &f, texture2d<float> env_map)\n"
"{\n"
"	if (f.env.y > 0)\n"
"	{\n"
"		float c = cos(f.env.z);\n"
"		float sn = sin(f.env.z);\n"
"		float3 r = float3(c * d.x + sn * d.z, d.y, -sn * d.x + c * d.z);\n"
"		float2 uv = float2(atan2(r.x, -r.z) / (2 * M_PI_F) + 0.5f,\n"
"			acos(clamp(r.y, -1.0f, 1.0f)) / M_PI_F);\n"
"		return (env_map.sample(env_sampler, uv, level(0)).rgb * f.env.x);\n"
"	}\n"
"	float	up = clamp(d.y, 0.0f, 1.0f);\n"
"\n"
"	return (mix(float3(0.85f, 0.9f, 1.0f), float3(0.32f, 0.5f, 0.85f),\n"
"		pow(up, 0.6f)) * 1.2f);\n"
"}\n"
"\n"
"/*\n"
"** Curva ACES (aproximacion de Narkowicz): comprime las luces altas como una\n"
"** camara en vez de recortarlas a blanco.\n"
"*/\n"
"\n"
"static float3	tonemap(float3 x)\n"
"{\n"
"	return (clamp((x * (2.51f * x + 0.03f)) / (x * (2.43f * x + 0.59f)\n"
"		+ 0.14f), 0.0f, 1.0f));\n"
"}\n"
"\n"
"static uint		hash(uint x)\n"
"{\n"
"	x ^= x >> 16;\n"
"	x *= 0x7feb352dU;\n"
"	x ^= x >> 15;\n"
"	x *= 0x846ca68bU;\n"
"	x ^= x >> 16;\n"
"	return (x);\n"
"}\n"
"\n"
"/*\n"
"** Oclusion ambiental: fraccion de f.ao_rays rayos cortos (AO_RADIUS) hacia\n"
"** el hemisferio de la normal que no chocan con nada. Distribucion coseno\n"
"** con una rotacion aleatoria por pixel.\n"
"*/\n"
"\n"
"static float	ambient_occlusion(float3 p, float3 n, uint seed,\n"
"					constant t_gpu_frame &f, device const t_gpu_object *objs,\n"
"					ACCEL_DECL)\n"
"{\n"
"	float3	t = normalize(fabs(n.x) > 0.5f ? cross(n, float3(0, 1, 0))\n"
"		: cross(n, float3(1, 0, 0)));\n"
"	float3	b = cross(n, t);\n"
"	float	r0 = (hash(seed) & 0xffff) / 65536.0f;\n"
"	float	r1 = (hash(seed * 7 + 3) & 0xffff) / 65536.0f;\n"
"	int		open = 0;\n"
"\n"
"	for (int i = 0; i < f.ao_rays; i++)\n"
"	{\n"
"		float u = fract(r0 + i * 0.618034f);\n"
"		float v = fract(r1 + (i + 0.5f) / f.ao_rays);\n"
"		float r = sqrt(v);\n"
"		float phi = 2 * M_PI_F * u;\n"
"		float3 dir = t * (r * cos(phi)) + b * (r * sin(phi)) + n * sqrt(1 - v);\n"
"		open += intersect(p, dir, f, objs, ACCEL_ARGS, AO_RADIUS, true).id < 0;\n"
"	}\n"
"	return ((float)open / f.ao_rays);\n"
"}\n"
"\n"
"struct			Surf\n"
"{\n"
"	float3		p;\n"
"	float3		n;\n"
"	float3		ng;\n"
"	float3		albedo;\n"
"	float		refl;\n"
"	float		spec;\n"
"	float		rough;\n"
"	float		metal;\n"
"	bool		pbr;\n"
"};\n"
"\n"
"/*\n"
"** Datos de la superficie tocada: punto (ya desplazado para no chocar\n"
"** consigo mismo), normal de sombreado, normal geometrica y material.\n"
"*/\n"
"\n"
"static Surf		surface(Hit hit, float3 o, float3 d, float cone,\n"
"					constant t_gpu_frame &f, device const t_gpu_object *objs,\n"
"					ACCEL_DECL, float lod_bias = 0)\n"
"{\n"
"	Surf	s;\n"
"\n"
"	s.p = o + hit.t * d;\n"
"#ifdef HW_RT\n"
"	if (hit.mesh)\n"
"	{\n"
"		device const t_gpu_tri &t = tris[hit.id];\n"
"		/*\n"
"		** Instancia: giro alrededor de Y (cos, sin) y desplazamiento en X/Z.\n"
"		** Las posiciones del buffer estan en el espacio del modelo.\n"
"		*/\n"
"		float4 it = insts[hit.inst];\n"
"		float3 p0 = inst_point(mesh_pos[hit.id * 3], it);\n"
"		float3 p1 = inst_point(mesh_pos[hit.id * 3 + 1], it);\n"
"		float3 p2 = inst_point(mesh_pos[hit.id * 3 + 2], it);\n"
"		float3 cr = cross(p1 - p0, p2 - p0);\n"
"		s.ng = normalize(cr);\n"
"		if (dot(s.ng, d) > 0)\n"
"			s.ng = -s.ng;\n"
"		float2 b = hit.bary;\n"
"		float3 ns = inst_rotate(unpack_normal(t.n[0]) * (1 - b.x - b.y)\n"
"			+ unpack_normal(t.n[1]) * b.x + unpack_normal(t.n[2]) * b.y, it);\n"
"		s.n = length_squared(ns) > 1e-4f ? normalize(ns) : s.ng;\n"
"		if (dot(s.n, s.ng) < 0)\n"
"			s.n = -s.n;\n"
"		device const GpuMaterial &m = mats[t.material];\n"
"		s.albedo = m.kd.rgb;\n"
"		s.rough = m.roughness;\n"
"		s.metal = m.metallic;\n"
"		s.pbr = true;\n"
"		/*\n"
"		** Nivel de mipmap por \"cono de rayo\": cuanto mas lejos y mas de\n"
"		** canto, mas grande es la huella del pixel en la textura. lod0 es\n"
"		** para una textura de 1x1; cada mapa suma su propio tamano.\n"
"		*/\n"
"		float2 e1 = float2(t.uv[2] - t.uv[0], t.uv[3] - t.uv[1]);\n"
"		float2 e2 = float2(t.uv[4] - t.uv[0], t.uv[5] - t.uv[1]);\n"
"		float uv_det = e1.x * e2.y - e2.x * e1.y;\n"
"		float lod0 = 0.5f * log2(max(fabs(uv_det), 1e-20f)\n"
"			/ max(length(cr), 1e-12f))\n"
"			+ log2(cone * f.spread / max(fabs(dot(s.ng, d)), 0.1f)) + lod_bias;\n"
"		float2 uv = tri_uv(t, b);\n"
"		if (m.flags & MAT_TEXTURE)\n"
"			s.albedo *= m.diffuse.sample(tex_sampler, uv, level(max(lod0\n"
"				+ 0.5f * log2((float)m.diffuse.get_width()\n"
"				* m.diffuse.get_height()), 0.0f))).rgb;\n"
"		if (m.flags & MAT_ROUGH)\n"
"			s.rough = m.rough.sample(tex_sampler, uv, level(max(lod0 + 0.5f\n"
"				* log2((float)m.rough.get_width() * m.rough.get_height()),\n"
"				0.0f))).r;\n"
"		if (m.flags & MAT_METAL)\n"
"			s.metal = m.metal.sample(tex_sampler, uv, level(max(lod0 + 0.5f\n"
"				* log2((float)m.metal.get_width() * m.metal.get_height()),\n"
"				0.0f))).r;\n"
"		if ((m.flags & MAT_NORMAL) && fabs(uv_det) > 1e-12f)\n"
"		{\n"
"			/*\n"
"			** Mapa de normales (convencion OpenGL): base tangente sacada de\n"
"			** las posiciones y coordenadas de textura del triangulo.\n"
"			*/\n"
"			float3 tn = m.normal.sample(tex_sampler, uv, level(max(lod0\n"
"				+ 0.5f * log2((float)m.normal.get_width()\n"
"				* m.normal.get_height()), 0.0f))).rgb * 2 - 1;\n"
"			float3 tg = ((p1 - p0) * e2.y - (p2 - p0) * e1.y) / uv_det;\n"
"			float3 bt = ((p2 - p0) * e1.x - (p1 - p0) * e2.x) / uv_det;\n"
"			tg = tg - s.n * dot(s.n, tg);\n"
"			if (length_squared(tg) > 1e-12f)\n"
"			{\n"
"				tg = normalize(tg);\n"
"				float3 bn = cross(s.n, tg) * (dot(cross(s.n, tg), bt) < 0\n"
"					? -1.0f : 1.0f);\n"
"				float3 nm = normalize(tg * tn.x + bn * tn.y + s.n * max(tn.z,\n"
"					0.05f));\n"
"				if (dot(nm, s.ng) > 0.02f)\n"
"					s.n = nm;\n"
"			}\n"
"		}\n"
"		s.rough = clamp(s.rough, 0.03f, 1.0f);\n"
"		s.metal = clamp(s.metal, 0.0f, 1.0f);\n"
"		s.refl = 0;\n"
"		s.spec = MESH_SPECULAR;\n"
"	}\n"
"	else\n"
"#endif\n"
"	{\n"
"		device const t_gpu_object &obj = objs[hit.id];\n"
"		s.n = normalize(hit.normal);\n"
"		if (dot(s.n, d) > 0)\n"
"			s.n = -s.n;\n"
"		s.ng = s.n;\n"
"		s.albedo = obj.color.xyz;\n"
"		s.refl = obj.reflect;\n"
"		s.spec = SPECULAR;\n"
"		s.rough = 1;\n"
"		s.metal = 0;\n"
"		s.pbr = false;\n"
"	}\n"
"	/*\n"
"	** El error de coma flotante crece con la distancia al origen: un\n"
"	** desplazamiento fijo deja \"acne\" (puntos negros) en escenas grandes.\n"
"	*/\n"
"	s.p += s.ng * EPSILON * max(1.0f, length(s.p) * 0.1f);\n"
"	return (s);\n"
"}\n"
"\n"
"/*\n"
"** Modelo de material fisico: difuso de Lambert + reflexion especular GGX\n"
"** (microfacetas) con Fresnel de Schlick y sombreado de Smith. Las luces van\n"
"** en unidades \"pi\" (difuso = albedo * luz * coseno), asi que el especular se\n"
"** multiplica por pi para mantener la proporcion.\n"
"*/\n"
"\n"
"static float3	fresnel(float3 f0, float c)\n"
"{\n"
"	return (f0 + (1 - f0) * pow(clamp(1 - c, 0.0f, 1.0f), 5.0f));\n"
"}\n"
"\n"
"static float	ggx_d(float nh, float a)\n"
"{\n"
"	float a2 = a * a;\n"
"	float k = nh * nh * (a2 - 1) + 1;\n"
"\n"
"	return (a2 / (M_PI_F * k * k));\n"
"}\n"
"\n"
"static float	smith_g1(float c, float a)\n"
"{\n"
"	float a2 = a * a;\n"
"\n"
"	return (2 * c / (c + sqrt(a2 + (1 - a2) * c * c)));\n"
"}\n"
"\n"
"static float3	brdf_pi(Surf s, float3 v, float3 l)\n"
"{\n"
"	float3	h = normalize(v + l);\n"
"	float	nl = max(dot(s.n, l), 0.0f);\n"
"	float	nv = max(dot(s.n, v), 1e-4f);\n"
"	float	a = s.rough * s.rough;\n"
"	float3	f0 = mix(float3(0.04f), s.albedo, s.metal);\n"
"	float3	F = fresnel(f0, max(dot(v, h), 0.0f));\n"
"	float3	spec = ggx_d(max(dot(s.n, h), 0.0f), a) * smith_g1(nl, a)\n"
"		* smith_g1(nv, a) / (4 * nv * max(nl, 1e-4f)) * F * M_PI_F;\n"
"\n"
"	return ((1 - F) * (1 - s.metal) * s.albedo + spec);\n"
"}\n"
"\n"
"static float	rand01(uint seed)\n"
"{\n"
"	return ((hash(seed) & 0xffffff) / 16777216.0f);\n"
"}\n"
"\n"
"/*\n"
"** Luz directa: lamparas del .rt y, si hay HDRI, el sol como un disco con su\n"
"** tamano real: cada rayo de sombra apunta a un punto al azar del disco, y\n"
"** de ahi salen las sombras con penumbra.\n"
"*/\n"
"\n"
"static float3	direct_light(Surf s, float3 d, bool shadows,\n"
"					constant t_gpu_frame &f, device const t_gpu_object *objs,\n"
"					device const t_gpu_light *lights, ACCEL_DECL,\n"
"					uint seed = 0)\n"
"{\n"
"	float3	local = float3(0);\n"
"	float3	v = -d;\n"
"\n"
"	for (int i = 0; i < f.nlights; i++)\n"
"	{\n"
"		float3 tolight = lights[i].position.xyz - s.p;\n"
"		float dist = length(tolight);\n"
"		float3 l = tolight / dist;\n"
"		float ndl = dot(s.n, l);\n"
"		if (ndl <= 0 || (shadows\n"
"			&& intersect(s.p, l, f, objs, ACCEL_ARGS, dist, true).id >= 0))\n"
"			continue ;\n"
"		float3 lc = lights[i].color.xyz;\n"
"		if (s.pbr)\n"
"		{\n"
"			local += lc * ndl * brdf_pi(s, v, l);\n"
"			continue ;\n"
"		}\n"
"		local += s.albedo * lc * ndl;\n"
"		float ndh = dot(s.n, normalize(l - d));\n"
"		if (ndh > 0)\n"
"			local += lc * s.spec * pow(ndh, SHININESS);\n"
"	}\n"
"	if (f.sun_color.w > 0)\n"
"	{\n"
"		float3	w = f.sun_dir.xyz;\n"
"		float3	t = normalize(fabs(w.y) < 0.9f ? cross(w, float3(0, 1, 0))\n"
"			: cross(w, float3(1, 0, 0)));\n"
"		float3	b = cross(w, t);\n"
"		float	u1 = rand01(seed * 3 + 11);\n"
"		float	u2 = rand01(seed * 5 + 29);\n"
"		float	ct = 1 - u1 * (1 - f.sun_dir.w);\n"
"		float	st = sqrt(max(0.0f, 1 - ct * ct));\n"
"		float3	l = normalize(w * ct + t * (st * cos(2 * M_PI_F * u2))\n"
"			+ b * (st * sin(2 * M_PI_F * u2)));\n"
"		float	ndl = dot(s.n, l);\n"
"		if (ndl > 0 && dot(s.ng, l) > 0 && (!shadows\n"
"			|| intersect(s.p, l, f, objs, ACCEL_ARGS, NOHIT, true).id < 0))\n"
"			local += f.sun_color.rgb * ndl * (s.pbr ? brdf_pi(s, v, l)\n"
"				: s.albedo);\n"
"	}\n"
"	return (local);\n"
"}\n"
"\n"
"static float3	trace(float3 o, float3 d, constant t_gpu_frame &f,\n"
"					device const t_gpu_object *objs,\n"
"					device const t_gpu_light *lights,\n"
"					ACCEL_DECL, uint seed, thread float &first_t)\n"
"{\n"
"	float3 color = float3(0);\n"
"	first_t = NOHIT;\n"
"	float3 weight = float3(1);\n"
"	float cone = 0;\n"
"\n"
"	for (int depth = 0; depth <= MAX_DEPTH; depth++)\n"
"	{\n"
"		Hit hit = intersect(o, d, f, objs, ACCEL_ARGS, NOHIT, false);\n"
"		if (hit.id < 0)\n"
"		{\n"
"			if (f.ntris > 0)\n"
"				color += weight * sky(d, f, env_map);\n"
"			break ;\n"
"		}\n"
"		cone += hit.t;\n"
"		if (depth == 0)\n"
"			first_t = hit.t;\n"
"		Surf s = surface(hit, o, d, cone, f, objs, ACCEL_ARGS);\n"
"		float3 local = s.albedo * f.ambient.xyz;\n"
"		if (f.ntris > 0 && depth == 0)\n"
"			local *= ambient_occlusion(s.p, s.n, seed, f, objs, ACCEL_ARGS);\n"
"		bool shadows = max3(weight.x, weight.y, weight.z) >= SHADOW_MIN_WEIGHT;\n"
"		local += direct_light(s, d, shadows, f, objs, lights, ACCEL_ARGS);\n"
"		if (s.refl > 0 && depth < MAX_DEPTH)\n"
"		{\n"
"			color += weight * (1 - s.refl) * local;\n"
"			weight *= s.refl;\n"
"			o = s.p;\n"
"			d = reflect(d, s.n);\n"
"		}\n"
"		else\n"
"		{\n"
"			color += weight * local;\n"
"			break ;\n"
"		}\n"
"	}\n"
"	return (color);\n"
"}\n"
"\n"
"static float3	cosine_dir(float3 n, uint seed)\n"
"{\n"
"	float3	t = normalize(fabs(n.x) > 0.5f ? cross(n, float3(0, 1, 0))\n"
"		: cross(n, float3(1, 0, 0)));\n"
"	float3	b = cross(n, t);\n"
"	float	u = (hash(seed) & 0xffffff) / 16777216.0f;\n"
"	float	v = (hash(seed * 31 + 17) & 0xffffff) / 16777216.0f;\n"
"	float	r = sqrt(v);\n"
"	float	phi = 2 * M_PI_F * u;\n"
"\n"
"	return (t * (r * cos(phi)) + b * (r * sin(phi)) + n * sqrt(1 - v));\n"
"}\n"
"\n"
"/*\n"
"** Direccion reflejada muestreando la distribucion GGX (microfaceta al azar\n"
"** alrededor de la normal segun la rugosidad).\n"
"*/\n"
"\n"
"static float3	ggx_dir(float3 n, float3 v, float a, uint seed,\n"
"					thread float3 &h)\n"
"{\n"
"	float	u1 = rand01(seed * 13 + 7);\n"
"	float	u2 = rand01(seed * 17 + 3);\n"
"	float	ct = sqrt((1 - u1) / (1 + (a * a - 1) * u1));\n"
"	float	st = sqrt(max(0.0f, 1 - ct * ct));\n"
"	float3	t = normalize(fabs(n.x) > 0.5f ? cross(n, float3(0, 1, 0))\n"
"		: cross(n, float3(1, 0, 0)));\n"
"	float3	b = cross(n, t);\n"
"\n"
"	h = normalize(t * (st * cos(2 * M_PI_F * u2)) + b * (st * sin(2 * M_PI_F\n"
"		* u2)) + n * ct);\n"
"	return (reflect(-v, h));\n"
"}\n"
"\n"
"/*\n"
"** Iluminacion global: luz directa (lamparas, sol con penumbra) + GI_BOUNCES\n"
"** rebotes. En cada rebote se elige entre la parte difusa (direccion coseno)\n"
"** y la especular (direccion GGX), con mas probabilidad de especular cuanto\n"
"** mas metalico y liso es el material. Devuelve tambien las guias del\n"
"** denoiser del primer impacto.\n"
"*/\n"
"\n"
"static float3	trace_gi(float3 o, float3 d, constant t_gpu_frame &f,\n"
"					device const t_gpu_object *objs,\n"
"					device const t_gpu_light *lights, ACCEL_DECL, uint seed,\n"
"					thread float &first_t, thread float3 &first_albedo,\n"
"					thread float3 &first_normal, thread float3 &first_spec,\n"
"					thread float &first_rough)\n"
"{\n"
"	float3	color = float3(0);\n"
"	float3	weight = float3(1);\n"
"	float	cone = 0;\n"
"\n"
"	first_t = NOHIT;\n"
"	first_albedo = float3(1);\n"
"	first_normal = float3(0, 0, 1);\n"
"	first_spec = float3(0.04f);\n"
"	first_rough = 1;\n"
"	for (int depth = 0; depth <= GI_BOUNCES; depth++)\n"
"	{\n"
"		Hit hit = intersect(o, d, f, objs, ACCEL_ARGS, NOHIT, false);\n"
"		if (hit.id < 0)\n"
"		{\n"
"			color += weight * sky(d, f, env_map) * (depth == 0 || f.env.y > 0\n"
"				? 1.0f : SKY_LIGHT);\n"
"			break ;\n"
"		}\n"
"		cone += hit.t;\n"
"		/*\n"
"		** La luz rebotada no necesita texturas nitidas: en los rebotes se lee\n"
"		** un nivel de mipmap mas borroso (menos memoria).\n"
"		*/\n"
"		Surf s = surface(hit, o, d, cone, f, objs, ACCEL_ARGS,\n"
"			depth > 0 ? BOUNCE_LOD_BIAS : 0.0f);\n"
"		float3 f0 = mix(float3(0.04f), s.albedo, s.metal);\n"
"		if (depth == 0)\n"
"		{\n"
"			first_t = hit.t;\n"
"			first_albedo = s.albedo * (1 - s.metal);\n"
"			first_normal = s.n;\n"
"			first_spec = f0;\n"
"			first_rough = s.rough;\n"
"		}\n"
"		color += weight * direct_light(s, d, true, f, objs, lights, ACCEL_ARGS,\n"
"			seed + depth * 7919);\n"
"		if (depth == GI_BOUNCES)\n"
"			break ;\n"
"		float3 v = -d;\n"
"		float ps = s.pbr ? clamp(mix(0.15f, 1.0f, s.metal) * (1.2f\n"
"			- s.rough), 0.1f, 0.95f) : 0.0f;\n"
"		o = s.p;\n"
"		if (rand01(seed * 19 + depth * 31 + 5) < ps)\n"
"		{\n"
"			float3 h;\n"
"			float a = s.rough * s.rough;\n"
"			d = ggx_dir(s.n, v, a, seed + depth * 4513, h);\n"
"			float nl = dot(s.n, d);\n"
"			float nv = max(dot(s.n, v), 1e-4f);\n"
"			if (nl <= 0 || dot(d, s.ng) <= 0)\n"
"				break ;\n"
"			float vh = max(dot(v, h), 1e-4f);\n"
"			weight *= fresnel(f0, vh) * smith_g1(nl, a) * smith_g1(nv, a) * vh\n"
"				/ (nv * max(dot(s.n, h), 1e-4f)) / ps;\n"
"		}\n"
"		else\n"
"		{\n"
"			d = cosine_dir(s.n, seed + depth * 7919);\n"
"			if (dot(d, s.ng) <= 0)\n"
"				break ;\n"
"			weight *= s.albedo * (1 - s.metal) * (s.pbr ? 1 - fresnel(f0,\n"
"				max(dot(s.n, v), 0.0f)) : float3(1)) / (1 - ps);\n"
"		}\n"
"	}\n"
"	return (color);\n"
"}\n"
"\n"
"static float	channel_diff(float4 a, float4 b)\n"
"{\n"
"	float3 d = fabs(a.rgb - b.rgb);\n"
"\n"
"	return (max3(d.x, d.y, d.z));\n"
"}\n"
"\n"
"/*\n"
"** pass 0: normal (f.samples x f.samples rayos por pixel).\n"
"** pass 1 y 2: antialiasing adaptativo. El 1 calcula 1 rayo por pixel; el\n"
"** 2 solo repite con f.samples x f.samples los pixeles que difieren de algun\n"
"** vecino (bordes); el resto se copia tal cual.\n"
"*/\n"
"\n"
"kernel void		render(texture2d<float, access::write> out [[texture(0)]],\n"
"					texture2d<float, access::read> base [[texture(1)]],\n"
"					texture2d<float, access::write> depth_out [[texture(2)]],\n"
"					texture2d<float, access::write> motion_out [[texture(3)]],\n"
"					texture2d<float, access::write> albedo_out [[texture(4)]],\n"
"					texture2d<float, access::write> normal_out [[texture(5)]],\n"
"					texture2d<float, access::write> rough_out [[texture(6)]],\n"
"					texture2d<float, access::write> spec_out [[texture(7)]],\n"
"					constant t_gpu_frame &f [[buffer(0)]],\n"
"					device const t_gpu_object *objs [[buffer(1)]],\n"
"					device const t_gpu_light *lights [[buffer(2)]],\n"
"#ifdef HW_RT\n"
"					primitive_acceleration_structure accel [[buffer(3)]],\n"
"					intersection_function_table<> table [[buffer(4)]],\n"
"					MESH_ACCEL mesh_accel [[buffer(8)]],\n"
"					intersection_function_table<MESH_TAGS> mesh_table [[buffer(9)]],\n"
"					device const t_gpu_tri *tris [[buffer(10)]],\n"
"					device const GpuMaterial *mats [[buffer(11)]],\n"
"					device const packed_float3 *mesh_pos [[buffer(12)]],\n"
"					device const float4 *insts [[buffer(13)]],\n"
"#endif\n"
"					texture2d<float> env_map [[texture(8)]],\n"
"#ifdef HW_RT\n"
"#else\n"
"					device const t_gpu_node *nodes [[buffer(3)]],\n"
"#endif\n"
"					uint2 gid [[thread_position_in_grid]])\n"
"{\n"
"	float w = out.get_width();\n"
"	float h = out.get_height();\n"
"\n"
"	if (gid.x >= w || gid.y >= h)\n"
"		return ;\n"
"	if (f.pass == 5)\n"
"	{\n"
"		/*\n"
"		** Salida del denoiser (luz lineal) -> tonemapping + gamma.\n"
"		*/\n"
"		float3 c = tonemap(base.read(gid).rgb);\n"
"		out.write(float4(pow(c, 1 / GAMMA), 1), gid);\n"
"		return ;\n"
"	}\n"
"	if (f.pass == 4)\n"
"	{\n"
"		/*\n"
"		** Iluminacion global para el denoiser de MetalFX: luz lineal con\n"
"		** grano mas las guias (color de superficie, normal, rugosidad,\n"
"		** profundidad de recorte y movimiento).\n"
"		*/\n"
"		float depth = w / (2 * tan(f.fov * M_PI_F / 360));\n"
"		float px = gid.x + f.jitter.x;\n"
"		float py = gid.y + f.jitter.y;\n"
"		float3 d = normalize(f.forward.xyz * depth\n"
"			+ f.right.xyz * (px - w / 2) + f.up.xyz * (h / 2 - py));\n"
"		float first_t;\n"
"		float3 alb;\n"
"		float3 nrm;\n"
"		float3 spc;\n"
"		float rgh;\n"
"		float3 c = trace_gi(f.origin.xyz, d, f, objs, lights, ACCEL_ARGS,\n"
"			hash(gid.x * 1973 + gid.y * 9277 + f.frame * 104729), first_t,\n"
"			alb, nrm, spc, rgh);\n"
"		out.write(float4(c * (f.env.y > 0 ? f.env.w : GI_EXPOSURE), 1), gid);\n"
"		albedo_out.write(float4(alb, 1), gid);\n"
"		normal_out.write(float4(nrm, 0), gid);\n"
"		rough_out.write(float4(rgh), gid);\n"
"		spec_out.write(float4(spc, 1), gid);\n"
"		float3 world = f.origin.xyz + d * min(first_t, 1e5f);\n"
"		float3 v = world - f.prev_origin.xyz;\n"
"		float z = dot(v, f.prev_forward.xyz);\n"
"		float2 prev = float2(dot(v, f.prev_right.xyz), -dot(v, f.prev_up.xyz))\n"
"			* (depth / max(z, 1e-4f)) + float2(w / 2, h / 2);\n"
"		float2 motion = z > 1e-4f ? prev - float2(px, py) : float2(0);\n"
"		motion_out.write(float4(motion / float2(w, h), 0, 0), gid);\n"
"		float vz = min(first_t, 1e5f) * dot(d, f.forward.xyz);\n"
"		depth_out.write(float4(first_t < NOHIT ? clamp(CLIP_FAR * (vz - CLIP_NEAR)\n"
"			/ ((CLIP_FAR - CLIP_NEAR) * vz), 0.0f, 1.0f) : 1.0f), gid);\n"
"		return ;\n"
"	}\n"
"	if (f.pass == 3)\n"
"	{\n"
"		/*\n"
"		** Entrada del reescalado temporal (MetalFX): 1 rayo desplazado por\n"
"		** el jitter de esta imagen, mas la profundidad (Z invertida) y el\n"
"		** vector de movimiento: donde estaba este punto en la imagen anterior.\n"
"		*/\n"
"		float depth = w / (2 * tan(f.fov * M_PI_F / 360));\n"
"		float px = gid.x + f.jitter.x;\n"
"		float py = gid.y + f.jitter.y;\n"
"		float3 d = normalize(f.forward.xyz * depth\n"
"			+ f.right.xyz * (px - w / 2) + f.up.xyz * (h / 2 - py));\n"
"		float first_t;\n"
"		float3 c = trace(f.origin.xyz, d, f, objs, lights, ACCEL_ARGS,\n"
"			hash(gid.x * 1973 + gid.y * 9277 + f.frame * 104729), first_t);\n"
"		c = f.ntris > 0 ? tonemap(c * EXPOSURE) : c;\n"
"		out.write(float4(pow(clamp(c, 0.0, 1.0), 1 / GAMMA), 1), gid);\n"
"		float3 world = f.origin.xyz + d * min(first_t, 1e5f);\n"
"		float3 v = world - f.prev_origin.xyz;\n"
"		float z = dot(v, f.prev_forward.xyz);\n"
"		float2 prev = float2(dot(v, f.prev_right.xyz), -dot(v, f.prev_up.xyz))\n"
"			* (depth / max(z, 1e-4f)) + float2(w / 2, h / 2);\n"
"		float2 motion = z > 1e-4f ? prev - float2(px, py) + f.jitter.zw\n"
"			: float2(0);\n"
"		motion_out.write(float4(motion / float2(w, h), 0, 0), gid);\n"
"		depth_out.write(float4(first_t < NOHIT ? clamp(0.05f / first_t, 0.0f,\n"
"			1.0f) : 0.0f), gid);\n"
"		return ;\n"
"	}\n"
"	if (f.pass == 2)\n"
"	{\n"
"		float4 c = base.read(gid);\n"
"		uint2 hi = uint2(w - 1, h - 1);\n"
"		float diff = 0;\n"
"		diff = max(diff, channel_diff(c, base.read(uint2(max((int)gid.x - 1, 0), gid.y))));\n"
"		diff = max(diff, channel_diff(c, base.read(uint2(min(gid.x + 1, hi.x), gid.y))));\n"
"		diff = max(diff, channel_diff(c, base.read(uint2(gid.x, max((int)gid.y - 1, 0)))));\n"
"		diff = max(diff, channel_diff(c, base.read(uint2(gid.x, min(gid.y + 1, hi.y)))));\n"
"		if (diff < EDGE)\n"
"		{\n"
"			out.write(c, gid);\n"
"			return ;\n"
"		}\n"
"	}\n"
"	int samples = f.pass == 1 ? 1 : f.samples;\n"
"	float depth = w / (2 * tan(f.fov * M_PI_F / 360));\n"
"	float3 color = float3(0);\n"
"	/*\n"
"	** En el refinado con un numero impar de muestras, la central coincide\n"
"	** con el rayo de la primera pasada: se reutiliza en vez de repetirlo.\n"
"	*/\n"
"	int reuse = f.pass == 2 && samples % 2 == 1 ? samples / 2 : -1;\n"
"	if (reuse >= 0)\n"
"		color = pow(base.read(gid).rgb, GAMMA);\n"
"	for (int sy = 0; sy < samples; sy++)\n"
"		for (int sx = 0; sx < samples; sx++)\n"
"		{\n"
"			if (sx == reuse && sy == reuse)\n"
"				continue ;\n"
"			float px = gid.x + (sx + 0.5) / samples - 0.5;\n"
"			float py = gid.y + (sy + 0.5) / samples - 0.5;\n"
"			float3 d = normalize(f.forward.xyz * depth\n"
"				+ f.right.xyz * (px - w / 2) + f.up.xyz * (h / 2 - py));\n"
"			float first_t;\n"
"			float3 c = trace(f.origin.xyz, d, f, objs, lights, ACCEL_ARGS,\n"
"				hash(gid.x * 1973 + gid.y * 9277 + (sy * samples + sx) * 26699\n"
"				+ f.frame * 104729), first_t);\n"
"			color += f.ntris > 0 ? tonemap(c * EXPOSURE) : c;\n"
"		}\n"
"	color /= samples * samples;\n"
"	out.write(float4(pow(clamp(color, 0.0, 1.0), 1 / GAMMA), 1), gid);\n"
"}\n"
;
